Repository requests/requests-oauthlib, pull requests merged in 2022-02, with the labels that each got.

#407 Have `OAuth2Session` correctly use the `self.verify` value if `verify` is not overridden in `fetch_token` and `refresh_token`.
  AUTHORS.rst
  HISTORY.rst
  requests_oauthlib/oauth2_session.py
Labels: bug

#409 `OAuth2Session` constructor now uses its `client.scope` when a `client` is provided and `scope` is not overridden.
  HISTORY.rst
  requests_oauthlib/oauth2_session.py
Labels: enhancement

#401 Prefer unittest.mock over external mock package
  setup.py
  tests/test_core.py
  tests/test_oauth1_session.py
  tests/test_oauth2_session.py
Labels: clean-up

#427 Don't pass 'files' through to token refresh
  requests_oauthlib/oauth2_session.py
Labels: bug

#438 Fix for #437 - remove erroneous charset param from Content-Type header
  requests_oauthlib/oauth2_session.py
Labels: bug

#474 Add support for Python 3.10
  .github/workflows/run-tests.yml
  AUTHORS.rst
  HISTORY.rst
  setup.py
  tox.ini
Labels: enhancement

#482 Fix typo in PyPI package name in installation instructions
  README.rst
  docs/index.rst
Labels: docs, clean-up

#433 Adding refresh_token_request and access_token_request compliance hooks
  requests_oauthlib/oauth2_session.py
  tests/test_compliance_fixes.py
Labels: enhancement
